// <auto-generated />
using System;
using Burse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Burse.Migrations
{
    [DbContext(typeof(BurseDBContext))]
    [Migration("20250426185846_AddTemplateDefault")]
    partial class AddTemplateDefault
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Burse.Models.BursaIstoric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Actiune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentarii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataModificare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etapa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentRecordId")
                        .HasColumnType("int");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipBursa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentRecordId");

                    b.ToTable("BursaIstoric");
                });

            modelBuilder.Entity("Burse.Models.FondBurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategorieBurse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValoreaLunara")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FondBurse");
                });

            modelBuilder.Entity("Burse.Models.FondBurseMeritRepartizat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Grupa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumaRamasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("bursaAlocatata")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("domeniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("programStudiu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FondBurseMeritRepartizat");
                });

            modelBuilder.Entity("Burse.Models.FormatiiStudii", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("An")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BursieriAIStatuluiRoman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaRM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaRomani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaUECEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElibiliB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facultatea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaRomani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaRp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaUECEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDeStudiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMEligibil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormatiiStudii");
                });

            modelBuilder.Entity("Burse.Models.GrupBursaEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Domeniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupBursa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupBursa");
                });

            modelBuilder.Entity("Burse.Models.GrupDomeniuEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Domeniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupDomeniu");
                });

            modelBuilder.Entity("Burse.Models.GrupProgramStudiiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Domeniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupProgramStudii");
                });

            modelBuilder.Entity("Burse.Models.StudentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<string>("Bursa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CO")
                        .HasColumnType("int");

                    b.Property<string>("Emplid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FondBurseMeritRepartizatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Media")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunctajAn")
                        .HasColumnType("int");

                    b.Property<int>("RO")
                        .HasColumnType("int");

                    b.Property<decimal>("SumaBursa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SursaFinantare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TC")
                        .HasColumnType("int");

                    b.Property<int>("TR")
                        .HasColumnType("int");

                    b.Property<string>("TaraCetatenie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FondBurseMeritRepartizatId");

                    b.ToTable("StudentRecord");
                });

            modelBuilder.Entity("Burse.Models.TemplatePDF.TemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TemplateEntity");
                });

            modelBuilder.Entity("Burse.Models.BursaIstoric", b =>
                {
                    b.HasOne("Burse.Models.StudentRecord", "StudentRecord")
                        .WithMany("IstoricBursa")
                        .HasForeignKey("StudentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentRecord");
                });

            modelBuilder.Entity("Burse.Models.StudentRecord", b =>
                {
                    b.HasOne("Burse.Models.FondBurseMeritRepartizat", "FondBurseMeritRepartizat")
                        .WithMany("Studenti")
                        .HasForeignKey("FondBurseMeritRepartizatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FondBurseMeritRepartizat");
                });

            modelBuilder.Entity("Burse.Models.FondBurseMeritRepartizat", b =>
                {
                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("Burse.Models.StudentRecord", b =>
                {
                    b.Navigation("IstoricBursa");
                });
#pragma warning restore 612, 618
        }
    }
}
