// <auto-generated />
using Burse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Burse.Migrations
{
    [DbContext(typeof(BurseDBContext))]
    partial class BurseDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Burse.Models.FondBurse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategorieBurse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValoreaLunara")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FondBurse", (string)null);
                });

            modelBuilder.Entity("Burse.Models.FormatiiStudii", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("An")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BursieriAIStatuluiRoman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaRM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaRomani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuTaxaUECEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElibiliB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facultatea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaRomani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaRp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaraTaxaUECEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDeStudiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RMEligibil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormatiiStudii", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
